language: c

install:
  - apt-get install mono-devel mono-gmcs
  - mozroots --import --machine --sync --ask-remove
  - yes certmgr -ssl -m https://go.microsoft.com
  - yes certmgr -ssl -m https://nugetgallery.blob.core.windows.net
  - yes certmgr -ssl -m https://nuget.org

script:
  - xbuild GlimpseSample.sln
